-- -- lua/lsp/init.lua
-- local M = {}
--
-- function M.setup()
--   -- Shared diagnostic config + key‑maps
--   local handlers = require("lsp.handlers")
--   handlers.setup()
--
--   -- Nothing else if lspconfig is missing
--   if not pcall(require, "lspconfig") then
--     return
--   end
--
--   -- One call that wires Mason + language‑extras (typescript‑tools, etc.)
--   require("lsp.mason").setup(handlers)
-- end
--
-- return M
